baseURL = "https://fboehm.us/"
languageCode = "en-us"
title = "Frederick Boehm's Website"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Frederick Boehm"
enableEmoji = true
publishDir = "docs"
disqusShortname = "fred3"
googleAnalytics = "UA-46757486-5"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  logo = "/images/vitruvian_mouse-small.jpg"
  description ="Biostatistics, genetics, medicine, open science"
  mailchimp = "https://fboehm.us19.list-manage.com/subscribe/post?u=40a2bbc4be9f309414d4d7089&amp;id=3feb11be28"
  mailprotector = "b_40a2bbc4be9f309414d4d7089_3feb11be28"

[params.author]
  name = "Frederick Boehm"
  thumbnail = "/images/FredBoehm-cr-smallsize.jpg"
  description = "Biostatistics, genetics, medicine, open science"

[params.index]
  picture = "/images/FredBoehm-cr-smallsize.jpg"
  title = "Frederick Boehm"
  subtitle = "Biostatistics, genetics, medicine, open science"
  mdtext = '''
I'm a biostatistician in Madison, Wisconsin, USA.\
I'm studying for a Ph.D. in statistics at the University of Wisconsin-Madison.\
My research is in statistical methods for systems genetics studies. In this \
setting, my colleagues and I developed a hypothesis test of pleiotropy vs. separate QTL\
in multiparental populations. We implemented our methods in the software package `qtl2pleio`.

I previously earned B.S. (2001) and M.D. (2007) degrees from the University of Wisconsin-Madison.\
I worked as a statistician with the Value-Added Research Center and the Genetics Coordinating Center.\

'''
  alertbar = true

[params.social]
  github = "fboehm"
#  linkedin = "<username>"
#  xing = "<username>"
#  medium = "<username>"
#  twitter = "<username>"

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 300
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/"
[[menu.main]]
    name = "software"
    identifier = "software"
    weight = 200
    url = "/static/software"
[[menu.main]]
    name = "teaching"
    identifier = "teaching"
    weight = 200
    url = "/static/teaching"
[[menu.main]]
    name = "publications"
    identifier = "publications"
    weight = 200
    url = "/static/publications"
[[menu.main]]
    name = "presentations"
    identifier = "presentations"
    weight = 200
    url = "/static/presentations"
