---
title: "Publications" 
author: "Frederick Boehm" 
output: html_document 
bibliography: boehm.bib 
csl: genetics.csl
---



```{r, echo = FALSE}
library(RefManageR)
```

```{r, echo = FALSE}
BibOptions(check.entries = FALSE, 
           cite.style = 'pandoc', 
           sorting = "ydnt", 
           style = "markdown", 
           max.names = 6, 
           hyperlink = "to.doc"
           )
ReadBib("boehm.bib", check = FALSE) -> boehm
```

## Peer-reviewed journal articles


```{r, results = 'asis', echo = FALSE}
NoCite(boehm)
arts <- boehm[bibtype = "article"]
PrintBibliography(arts[keywords = "peer-reviewed"], .opts = list(style = "text"))
```

## Pre-prints

```{r, results = "asis", echo = FALSE}
PrintBibliography(arts[keywords = "preprint"], .opts = list(style = "text"))
```



## Other articles


```{r, results = "asis", echo = FALSE}
PrintBibliography(arts[keywords = "other"], .opts = list(style = "text"))
```

## Edited books


```{r, results = "asis", echo = FALSE}
PrintBibliography(boehm[bibtype = "book"], .opts = list(style = "text"))
```



## Book chapters


```{r, results = "asis", echo = FALSE}
PrintBibliography(boehm[bibtype = "incollection"], .opts = list(style = "text"))
```



## Conference proceedings


```{r, results = "asis", echo = FALSE}
PrintBibliography(boehm[bibtype = "inproceedings"], .opts = list(style = "text"))
```
